# Generated by Django 4.2 on 2023-04-08 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tarea", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarea",
            name="persona",
        ),
        migrations.AddField(
            model_name="tarea",
            name="assigned",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tareas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tarea",
            name="owner",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_tareas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
